"""initial schema

Revision ID: 9fd9f9fb6d8d
Revises: 
Create Date: 2026-09-24 23:53:14.449317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fd9f9fb6d8d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('companyId', sa.String(length=40), nullable=False),
    sa.Column('userId', sa.String(length=40), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('module', sa.String(length=40), nullable=False),
    sa.Column('entityType', sa.String(length=40), nullable=False),
    sa.Column('entityId', sa.String(length=40), nullable=False),
    sa.Column('oldValues', sa.JSON(), nullable=True),
    sa.Column('newValues', sa.JSON(), nullable=True),
    sa.Column('ipAddress', sa.String(length=60), nullable=True),
    sa.Column('userAgent', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('errorMessage', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_companyId'), 'audit_logs', ['companyId'], unique=False)
    op.create_index(op.f('ix_audit_logs_createdAt'), 'audit_logs', ['createdAt'], unique=False)
    op.create_table('branches',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('companyId', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.String(length=40), nullable=False),
    sa.Column('updatedAt', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branches_companyId'), 'branches', ['companyId'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('companyId', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('createdAt', sa.String(length=40), nullable=False),
    sa.Column('updatedAt', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_companyId'), 'categories', ['companyId'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('legalName', sa.String(length=200), nullable=False),
    sa.Column('taxId', sa.String(length=40), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('createdAt', sa.String(length=40), nullable=False),
    sa.Column('updatedAt', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matrices',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('companyId', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('rows', sa.Integer(), nullable=False),
    sa.Column('cols', sa.Integer(), nullable=False),
    sa.Column('values', sa.JSON(), nullable=False),
    sa.Column('rowLabels', sa.JSON(), nullable=False),
    sa.Column('colLabels', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('sourceConfig', sa.JSON(), nullable=True),
    sa.Column('createdAt', sa.String(length=40), nullable=False),
    sa.Column('updatedAt', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matrices_companyId'), 'matrices', ['companyId'], unique=False)
    op.create_table('operations',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('companyId', sa.String(length=40), nullable=False),
    sa.Column('userId', sa.String(length=40), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('inputVectors', sa.JSON(), nullable=False),
    sa.Column('inputMatrices', sa.JSON(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('resultVectorId', sa.String(length=40), nullable=True),
    sa.Column('resultMatrixId', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('errorMessage', sa.Text(), nullable=True),
    sa.Column('executionTimeMs', sa.Float(), nullable=False),
    sa.Column('createdAt', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operations_companyId'), 'operations', ['companyId'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('companyId', sa.String(length=40), nullable=False),
    sa.Column('categoryId', sa.String(length=40), nullable=False),
    sa.Column('sku', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('unitPrice', sa.Float(), nullable=False),
    sa.Column('costPrice', sa.Float(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('minStock', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.String(length=40), nullable=False),
    sa.Column('updatedAt', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_companyId'), 'products', ['companyId'], unique=False)
    op.create_table('sales',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('companyId', sa.String(length=40), nullable=False),
    sa.Column('branchId', sa.String(length=40), nullable=False),
    sa.Column('userId', sa.String(length=40), nullable=False),
    sa.Column('saleNumber', sa.String(length=40), nullable=False),
    sa.Column('date', sa.String(length=40), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('tax', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.String(length=40), nullable=False),
    sa.Column('updatedAt', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_branchId'), 'sales', ['branchId'], unique=False)
    op.create_index(op.f('ix_sales_companyId'), 'sales', ['companyId'], unique=False)
    op.create_table('targets',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('companyId', sa.String(length=40), nullable=False),
    sa.Column('branchId', sa.String(length=40), nullable=True),
    sa.Column('productId', sa.String(length=40), nullable=True),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('targetValue', sa.Float(), nullable=False),
    sa.Column('achievedValue', sa.Float(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('createdAt', sa.String(length=40), nullable=False),
    sa.Column('updatedAt', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_targets_branchId'), 'targets', ['branchId'], unique=False)
    op.create_index(op.f('ix_targets_companyId'), 'targets', ['companyId'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('companyId', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('avatar', sa.Text(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('passwordHash', sa.String(length=200), nullable=True),
    sa.Column('createdAt', sa.String(length=40), nullable=False),
    sa.Column('updatedAt', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_companyId'), 'users', ['companyId'], unique=False)
    op.create_index(op.f('ix_users_dni'), 'users', ['dni'], unique=True)
    op.create_table('vectors',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('companyId', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('dimension', sa.Integer(), nullable=False),
    sa.Column('values', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('sourceConfig', sa.JSON(), nullable=True),
    sa.Column('createdAt', sa.String(length=40), nullable=False),
    sa.Column('updatedAt', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vectors_companyId'), 'vectors', ['companyId'], unique=False)
    op.create_table('inventory_movements',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('companyId', sa.String(length=40), nullable=False),
    sa.Column('branchId', sa.String(length=40), nullable=False),
    sa.Column('productId', sa.String(length=40), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=80), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('date', sa.String(length=40), nullable=False),
    sa.Column('createdAt', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['branchId'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['productId'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_movements_branchId'), 'inventory_movements', ['branchId'], unique=False)
    op.create_index(op.f('ix_inventory_movements_companyId'), 'inventory_movements', ['companyId'], unique=False)
    op.create_index(op.f('ix_inventory_movements_productId'), 'inventory_movements', ['productId'], unique=False)
    op.create_table('sale_details',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('saleId', sa.String(length=40), nullable=False),
    sa.Column('productId', sa.String(length=40), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unitPrice', sa.Float(), nullable=False),
    sa.Column('discount', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['productId'], ['products.id'], ),
    sa.ForeignKeyConstraint(['saleId'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_details_productId'), 'sale_details', ['productId'], unique=False)
    op.create_index(op.f('ix_sale_details_saleId'), 'sale_details', ['saleId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sale_details_saleId'), table_name='sale_details')
    op.drop_index(op.f('ix_sale_details_productId'), table_name='sale_details')
    op.drop_table('sale_details')
    op.drop_index(op.f('ix_inventory_movements_productId'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_companyId'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_branchId'), table_name='inventory_movements')
    op.drop_table('inventory_movements')
    op.drop_index(op.f('ix_vectors_companyId'), table_name='vectors')
    op.drop_table('vectors')
    op.drop_index(op.f('ix_users_dni'), table_name='users')
    op.drop_index(op.f('ix_users_companyId'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_targets_companyId'), table_name='targets')
    op.drop_index(op.f('ix_targets_branchId'), table_name='targets')
    op.drop_table('targets')
    op.drop_index(op.f('ix_sales_companyId'), table_name='sales')
    op.drop_index(op.f('ix_sales_branchId'), table_name='sales')
    op.drop_table('sales')
    op.drop_index(op.f('ix_products_companyId'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_operations_companyId'), table_name='operations')
    op.drop_table('operations')
    op.drop_index(op.f('ix_matrices_companyId'), table_name='matrices')
    op.drop_table('matrices')
    op.drop_table('companies')
    op.drop_index(op.f('ix_categories_companyId'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_branches_companyId'), table_name='branches')
    op.drop_table('branches')
    op.drop_index(op.f('ix_audit_logs_createdAt'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_companyId'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
